__Задача 1__

Даны значения величины заработной платы заемщиков банка (salary) и значения их поведенческого кредитного скоринга (scoring):

salary = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110]
scoring = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]

Используя только встроенные питоновские функции и структуры данных (т.е. без библиотек numpy, pandas и др.) найдите:
1. ковариацию этих двух величин,
2. коэффициент корреляции Пирсона.

Можно затем посчитать те же значения с использованием библиотек, чтобы проверить себя.

In [4]:
salary = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110]
scoring = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]

In [5]:
"расчет мат.ожидания"
def mean (X):
    
    mean = 0
    for i in X:
        mean += i
    return mean / len(X)

In [6]:
MX = mean(salary)
MY = mean(scoring)
MX, MY

(101.4, 709.9)

In [7]:
"Расчет ковариации"
sum = 0
for i in range(0, len(salary)):
        sum += ((salary[i] - MX) * (scoring[i] - MY))
cov = sum/(len(salary)-1)
cov

10175.377777777778

__коэффициент корреляции Пирсона__


Найдем сначала средн. квадр.отклонение по каждому массиву

In [8]:
import math as mt

In [9]:
def sko(X): 
    MX = mean(X)
    sum = 0
    for i in range(0, len(X)):
        sum += (X[i] - MX) ** 2
    return mt.sqrt(sum/len(X))
    

In [10]:
sko_salary = sko(salary)
sko_salary

59.115480206118605

In [11]:
sko_scoring =sko(scoring)
sko_scoring

174.55340157098058

Коэффиц. Пирсона

In [12]:
cov / (sko_scoring * sko_salary)

0.9861001023043512

__Найдем ковариацию с помощью numpy, pandas__

In [ ]:
import numpy as np
import pandas as pd
from pandas import DataFrame

In [ ]:
X = np.array(salary)
Y = np.array(scoring)

In [ ]:
MX = X.mean()
MY = Y.mean()

cov = ((X - MX) * (Y - MY)).sum() / (X.shape[0] - 1)
MX, MY, cov

In [67]:
np.cov(X, Y, ddof=1)

array([[ 3882.93333333, 10175.37777778],
       [10175.37777778, 33854.32222222]])

__найдем коэф. Пирсона с помощью numpay__

In [50]:
"проверим сред.квадр.отклонение"
X.std()

59.115480206118605

In [51]:
Y.std()

174.55340157098058

In [59]:
np.corrcoef(X,Y)

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

не поняла, почему не совпадает значение рассчитанное с помощью np.corrcoef(X,Y) с расчетом через формулу

In [68]:
corr = cov / (X.std() * Y.std())
corr

0.9861001023043514

__Задача 2__

Проведите тест на значимость коэффициента корреляции Пирсона, найденного в предыдущей задаче. Что для этого нужно знать:
* Нулевая гипотеза: реальный коэффициент корреляции равен 0. Альтернативная гипотеза двухсторонняя.
* Статистика: t = r * sqrt(n - 2) / sqrt(1 - r ** 2), где r - коэффициент корреляции Пирсона, посчитанный по выборке.
* В предположении верности нулевой гипотезы эта статистика имеет распределение Стьюдента с параметром df = n - 2.

In [78]:
from scipy import stats

Функция для формулы статистики

In [1]:
def statistic(n, corr):
    return (corr * np.sqrt(n - 2)) / np.sqrt(1 - (corr ** 2))

In [82]:
corr

0.9861001023043514

In [2]:
n = X.shape[0]
statistic(n, corr)

NameError: name 'X' is not defined

In [79]:
alpha = 0.05
t1 = stats.t.ppf(alpha / 2, df=n - 2)
t2 = stats.t.ppf(1 - alpha / 2, df=n - 2)

t1, t2

(-2.306004135033371, 2.3060041350333704)

__Вывод:__ коэф.корр.Пирсона не значим, так как полученное значение статистики (16,78) не лежит в интервале между квантилями

__Задача 3__

Измерены значения IQ выборки студентов, обучающихся в местных технических вузах:

131, 125, 115, 122, 131, 115, 107, 99, 125, 111

Известно, что в генеральной совокупности IQ распределен нормально. Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [96]:
iq = [131, 125, 115, 122, 131, 115, 107, 99, 125, 111]
iq_arr = np.array(iq)
iq_arr

array([131, 125, 115, 122, 131, 115, 107,  99, 125, 111])

Так как дисперисия неизвестна используем t статистику 

Эта статистика имеет распределение Стьюдента, поэтому
$$P \left( t_{\alpha / 2, \: n - 1} \leq t \leq t_{1 - \alpha / 2, \: n - 1} \right) = p$$


In [100]:
n = iq_arr.shape[0]

mean = iq_arr.mean()
std = iq_arr.std(ddof=1)

n, mean, std

(10, 118.1, 10.54566788359614)

Найдем квантили

In [101]:
p = 0.95
alpha = 1 - p

t1 = stats.t.ppf(alpha / 2, df=n - 1)
t2 = stats.t.ppf(1 - alpha / 2, df=n - 1)

t1, t2

(-2.2621571627409915, 2.2621571627409915)

Доверительный интервал

In [102]:
(mean + t1 * std / np.sqrt(n), mean + t2 * std / np.sqrt(n))

(110.55608365158724, 125.64391634841274)